import SelectCSS from '../css/select.css'
function SelectRoom() {
  return (
        <select className="select">
                <option>A204</option>
                <option>A205</option>
                <option>A206</option>
                <option>A207</option>
                <option>B103</option>
                <option>B104</option>
                <option>B105</option>
                <option>B106</option>
                <option>B107</option>
                <option>B108</option>
                <option>B109</option>
                <option>B110</option>
                <option>B113</option>
                <option>B208</option>
                <option>B209</option>
                <option>B210</option>
                <option>B216</option>
                <option>B218</option>
                <option>B224</option>
                <option>C106</option>
                <option>C107</option>
                <option>C109</option>
                <option>C110</option>
                <option>C227</option>
                <option>C228</option>
                <option>C433</option>
                <option>C434</option>
                <option>D125</option>
                <option>D126</option>
                <option>D127</option>
                <option>D229</option>
                <option>D230</option>
                <option>D231</option>
                <option>D336</option>
                <option>D337</option>
                <option>E107</option>
                <option>E108</option>
                <option>E110</option>
                <option>E111</option>
                <option>E116</option>
                <option>E119</option>
                <option>E120</option>
                <option>E333</option>
                <option>E334</option>
                <option>E335</option>
                <option>E336</option>
                <option>F111</option>
                <option>F112</option>
                <option>F114</option>
                <option>F404</option>
                <option>F405</option>
                <option>F426</option>
                <option>G104</option>
                <option>G105</option>
                <option>G106</option>
                <option>G107</option>
                <option>G117</option>
                <option>K203</option>
                <option>K204</option>
                <option>K206</option>
                <option>K207</option>
                <option>K208</option>
                <option>K210</option>
                <option>K211</option>
                <option>K212</option>
                <option>L205</option>
                <option>L208</option>
                <option>L225</option>
                <option>L229</option>
                <option>M205</option>
                <option>M211</option>
                <option>M212</option>
                <option>M213</option>
                <option>M221</option>
                <option>M222</option>
                <option>M223</option>
                <option>M224</option>
                <option>M315</option>
                <option>M316</option>
                <option>M317</option>
                <option>M321</option>
                <option>M322</option>
                <option>M323</option>
                <option>M324</option>
                <option>M402</option>
                <option>M403</option>
                <option>M404</option>
                <option>M405</option>
                <option>M415</option>
                <option>M416</option>
                <option>M417</option>
                <option>M418</option>
                <option>M421</option>
                <option>M422</option>
                <option>M423</option>
                <option>M424</option>
                <option>M515</option>
                <option>M516</option>
                <option>M517</option>
                <option>M518</option>
                <option>M521</option>
                <option>M522</option>
                <option>M523</option>
                <option>M524</option>
        </select>
  );
}

export default SelectRoom;